stages:
  - terraform
  - build
  - output

terraform:
  stage: terraform
  image: ubuntu:latest
  script:
    - apt-get update && apt-get install -y curl jq unzip
    - curl -o /tmp/terraform.zip -LO https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
    - unzip /tmp/terraform.zip -d /usr/local/bin/
    - chmod +x /usr/local/bin/terraform
    - terraform --version
    - mkdir -p ~/.aws
    - echo "[default]" > ~/.aws/credentials
    - echo "aws_access_key_id=$MY_AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
    - echo "aws_secret_access_key=$MY_AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
    - echo "aws_session_token=$MY_AWS_SESSION_TOKEN" >> ~/.aws/credentials
    - cat ~/.aws/credentials

    - terraform init
    - terraform plan -out=plan.tfplan
    - terraform apply -auto-approve plan.tfplan

    - echo "Saving Terraform outputs as CI/CD variables..."
    - echo "DB_URL=$(terraform output -raw db_url)" >> variables.env
    - echo "DB_USERNAME=$(terraform output -raw db_username)" >> variables.env
    - echo "DB_PASSWORD=$(terraform output -raw db_password)" >> variables.env
    - echo "EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip)" >> variables.env
    - echo "PRIVATE_KEY=$(terraform output -raw private_key | base64)" >> variables.env
    - cat variables.env

  artifacts:
    paths:
      - $CI_PROJECT_DIR/terraform.tfstate
    reports:
      dotenv: variables.env

  cache:
    key: "terraform-cache-2025-33dd"
    paths:
      - $CI_PROJECT_DIR/terraform.tfstate

build_image:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  stage: build
  only:
    - B-20-dockerize-and-deploy
  script:
    - echo "Logging into GitLab Container Registry..."
    - echo "$CI_JOB_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin $CI_REGISTRY

    - echo "Building Docker image with docker-compose..."
    - docker-compose build

    - IMAGE_NAME=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n 1)

    - docker tag $IMAGE_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

output_variables:
  stage: output
  script:
    - echo "Printing saved Terraform variables..."
    - echo "DB_URL=$DB_URL"
    - echo "DB_USERNAME=$DB_USERNAME"
    - echo "DB_PASSWORD=$DB_PASSWORD"
    - echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP"
    - echo "PRIVATE_KEY=$PRIVATE_KEY"
  dependencies:
    - terraform
  artifacts:
    paths:
      - variables.env